# Generated by Django 5.0 on 2024-05-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('nombre_figura', models.CharField(max_length=20)),
                ('anime', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('fecha_lanzamiento', models.DateField()),
                ('precio', models.IntegerField()),
                ('tamano', models.IntegerField()),
                ('id_figura', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
