# Generated by Django 5.0.6 on 2024-07-05 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='figura',
            name='nombre_figura',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.figura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
