# Generated by Django 5.0 on 2024-05-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_figura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='tamano',
            field=models.CharField(max_length=20),
        ),
    ]
