# Generated by Django 5.0.6 on 2024-07-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_anime_anime_alter_figura_nombre_figura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
