# Generated by Django 5.0.6 on 2024-07-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carritoitem_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='figuras/'),
        ),
    ]
