# Generated by Django 5.0.6 on 2024-07-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_figura_tamano'),
        ('core', '0004_figura_imagen'),
    ]

    operations = [
    ]
